version: '3'
services:
  hub-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHON_HANDLER_URL=http://python-handler:5000

  local-python-handler:
    build:
      context: ./integrations/python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"